### ISSUE TITLE
board清算算法

### ISSUE THREAD

**Issue by plantvsbirds** [lafickens/Billboard-Backend#7]
现在用的方式是循环match最大被欠钱数量／最大欠钱数量。然而不是最优
反例：
```
+71 -70 -1 +30 -30
```

然而如何定义最优？最优有多种定义方式。
似乎transaction总数有个最小值，按照现在这样做已经是最小值。。

**Comment by lafickens** [comment]
这个咱们在微信上讨论了，所以先close
